// A clear the clears log refused leaves the board as it was (the second review of PR 1967, 2026-09-21).
//
// The bug: `clr.onclick` adds the card's id to pendingCleared, released only when a payload OMITS the card; after
// `_clear_all` returns the ledger's fault every payload still lists it and the refusal frame named no request, so the
// card stayed hidden under a dialog saying every card is as it was. The kernel's frame now names the request (`op`, the
// batch's `itemIds`) and the feed's `err` handler releases those ids and repaints. Source-level pins (no jsdom for the
// feed renderer), mirroring feed-move-ack.
import { test } from "node:test";
import * as assert from "node:assert/strict";
import * as fs from "node:fs";
import * as path from "node:path";

const FEED = fs.readFileSync(path.resolve(process.cwd(), "..", "ui", "webview", "feed.ts"), "utf8");
const KERNEL = fs.readFileSync(path.resolve(process.cwd(), "..", "kernel", "kernel.py"), "utf8");
const FED = fs.readFileSync(path.resolve(process.cwd(), "..", "ui", "webview", "federation.ts"), "utf8");
const JUDGE = fs.readFileSync(path.resolve(process.cwd(), "..", "kernel", "judge.py"), "utf8");

test("client: the err handler releases the ids a refused clear names and repaints, before the latch re-arms", () => {
  const i = FEED.indexOf('} else if (m.type === "err" && typeof m.text === "string" && m.text) {');
  assert.ok(i >= 0);
  const h = FEED.slice(i, FEED.indexOf('} else if (m.type === "pickerOptions"', i));
  assert.match(h, /const refusedIds = Array\.isArray\(m\.itemIds\) \? m\.itemIds\.map\(String\) : \(op === "askClear" && itemId \? \[itemId\] : \[\]\);/);
  assert.match(h, /if \(\(op === "askClear" \|\| op === "askClearMany" \|\| op === "nodeOverride" \|\| op === "clearAll"\) && refusedIds\.length\) \{/, "the four clear requests");
  // the card returns in either window (the third review): the collapse class off, the cached item re-pushed, as Undo does
  assert.match(h, /for \(const id of refusedIds\) for \(const c of cardTwins\(id\)\) c\.classList\.remove\("dismissing"\);/, "the collapse class off by id (round ten: stack or no stack)");
  assert.match(h, /for \(const id of refusedIds\) \{ const it = clearedItems\.get\(id\); if \(it && !asks\.some\(\(a\) => a\.itemId === id\)\) asks\.push\(it\); \}/, "and the cards back from the page's record of what it cleared");
  // a refused undo reverts the optimistic restore (the verifier's medium A): the batch leaves asks and pendingRestored, is suppressed again and goes back on the stack
  assert.match(h, /\} else if \(op === "undoClear" && refusedIds\.length\) \{/);
  assert.match(h, /for \(const id of refusedIds\) \{ pendingRestored\.delete\(id\); pendingCleared\.add\(id\); \}/);
  assert.match(h, /if \(back\.length\) clearedStack\.push\(back\);/);
  assert.match(h, /if \(Array\.isArray\(m\.owedIds\) && m\.owedIds\.length\) clearedStack\.push\(\[\]\);/, "an entry standing for the owed ids above the last clear's (the sixth executed review): the next pop matches the kernel's");
  assert.match(h, /for \(const id of refusedIds\) pendingCleared\.delete\(id\);/, "the click's suppression lets go");
  assert.ok(h.indexOf("render();") > h.indexOf("pendingCleared.delete(id)"), "then the board repaints from the payload that still lists the card");
  assert.ok(h.indexOf("refusedIds") < h.indexOf('if (op === "apiRetry" && sid)'), "ahead of the latch re-arms the frame already drove");
  assert.match(h, /\} else if \(!op && sid\) rearmLatches\(\{ kind: "session", sid \}\);/, "an old kernel's reply naming a session and no request re-arms the session's latches; a store gesture's account (op rides) re-arms nothing (the fourth review of PR 1967, the manager's ruling: a latch is released only by the reply to the request that made it)");
  assert.doesNotMatch(FEED, /STORE_GESTURE_OPS/, "no request set widens the session re-arm");
  assert.match(h, /if \(m\.ok !== true\) window\.parent\?\.postMessage\(\{ romp: "notify", kind: "undelivered",/, "an information frame (the landed reorder) is a dialog and no bell entry (the round-four verifier)");
});

test("kernel: the clears-log refusal names the request the way _refuse_drive's frame does", () => {
  assert.match(KERNEL, /frame = \{"type": "err", "title": title, "text": text, "op": op or "",\s+"itemId": acct_ids\[0\] if acct_ids else "", "itemIds": list\(acct_ids\)\}\s+if sid_:\s+frame\["sid"\] = sid_/, "one frame shape for every account, each with its own ids; a session account names its session and an empty sid is omitted (the second contributor's review)");
  assert.match(KERNEL, /if ok:\s+frame\["ok"\] = True/, "and `ok` on an information frame alone (the round-four verifier)");
  assert.ok(KERNEL.includes('_gesture_store_refusal(client, "undo", _undo_clear(batch_out=_ub), ids=_ub, op=str(msg.get("type") or ""),\n                                   seq=_seq if isinstance(_seq, int) and not isinstance(_seq, bool) else None)'), "an undo names its op (the request's type), the batch it reached for (the verifier's medium A) and the feed's sequence (the post-merge review, M2)");
  // the double-fault window's other side (round four): the re-journal-first refusal fills the batch too, so the feed's revert has ids
  assert.match(KERNEL, /named = popped \+ \[i for i in owed_ids if i not in popped\][^\n]*\n\s+if batch_out is not None:\s+batch_out\.extend\(named\)\s+skipped\[LEDGER_REJOURNAL_AGAIN_KEY\] = \{"fault": _store_fault_copy\(e\), "ids": named\}\s+return skipped/);
  // the landed reorder tells the feed the popped batch was not restored this press (the third review's medium): an err frame, op undoClear, the popped ids
  assert.match(KERNEL, /skipped\[LEDGER_REORDER_KEY\] = \{"fault": "", "ids": popped, "landed": bool\(landed\), "owed": \[\] if landed else list\(not_back\), "stamps": int\(stamps\)\}/, "filed by _reorder after the flag step, worded for what happened (the fourth review)");
  assert.match(KERNEL, /_reorder\(not _not_back, _not_back, len\(\{_cur2\.get\(i\) for i in _not_back\}\) or 1\)/, "the owed cards came back only if every one did; the frame names the ones that did not and how many batches they sit in");
  assert.match(KERNEL, /_send\("Undo brought back earlier cards first",[\s\S]{0,400}ok=True\)/);
  assert.match(KERNEL, /_send\("Undo went to earlier cards first",[\s\S]{0,600}ok=True, owed=value\.get\("owed"\)/, "the words for an owed store still refusing, naming the owed ids");
  assert.match(KERNEL, /one Undo brings them back and the next the last clear\./, "the words name the condition, not a press count (the sixth executed review; the round-eight verifier), their subject derived from the ids that did not come back (the second contributor's review)");
  assert.match(KERNEL, /"owed": \[\] if landed else list\(not_back\), "stamps": int\(stamps\)/, "the ids that did NOT come back, and how many batches they sit in (the seventh executed review)");
  assert.match(KERNEL, /Once their stores can be read they take more than one Undo, since they were left at different points, and the last clear comes back after them\./, "no press count when they hold more than one stamp");
  // round eight: the kernel's stack rides every account and the page takes it as its own; a batch this page makes goes under the owed entries
  assert.match(KERNEL, /if key != LEDGER_READ_KEY:[\s\S]{0,1400}if not _lb\[0\]\[3\]:[^\n]*\n[^\n]*\n\s+frame\["batches"\], frame\["owedBatch"\], frame\["batchesTotal"\] = _lb\[0\]\[:3\]/, "every account carries the kernel's stack and the count before the bound, except while the log cannot be read: the read-fault account and any account beside it ship none (the round-one verifier of PR 2025)");
  assert.match(KERNEL, /cur, _rfault = _cleared_ids_read\(\)[^\n]*\n\s+if _rfault:\n\s+skipped\[LEDGER_READ_KEY\] = \{"fault": _rfault, "ids": \[\]\}/, "the undo's account describes its own read, taken with the set in one statement");
  assert.match(KERNEL, /def _cleared_ids\(\):[\s\S]{0,300}return _cleared_ids_read\(\)\[0\]/, "the set-only reader wraps the read that returns the fault too");
  assert.match(KERNEL, /def _undo_clear\(batch_out=None\):[\s\S]{0,3200}owed_ids = \[\][^\n]*\n\s+cur, _rfault = _cleared_ids_read\(\)[^\n]*\n\s+if _rfault:\n\s+skipped\[LEDGER_READ_KEY\] = \{"fault": _rfault, "ids": \[\]\}[^\n]*\n\s+return skipped[^\n]*\n[\s\S]{0,700}\n\s+with _OWED_LOCK:/, "the undo's own read comes FIRST: over a log it cannot read the press files the account and touches nothing, the re-journal-first block and the note rewrite behind it (the first contributor's round-one comment on PR 2025)");
  assert.match(FEED, /if \(storeOp && Array\.isArray\(m\.batches\) && !fromHost && !federatedPane\(\)\) \{/, "the local kernel's frame reconciles on a single-kernel pane; an old kernel's frame, and every frame on a federated pane, take the branches below (the round-nine verifier's ruling)");
  assert.match(FEED, /function federatedPane\(\): boolean \{ return attachedHosts\(\)\.size > 0; \}/, "read from federation's account of the attachment: the hosts pending or down, the merged payload's build map, the manager's host list; never sessions or cards (rounds twelve and thirteen)");
  assert.match(FEED, /function attachedHosts\(\): Set<string> \{[\s\S]{0,900}for \(const h of payloadHosts\) out\.add\(h\);[\s\S]{0,400}typeof fed\.hosts === "function"/, "its three sources");
  assert.match(FEED, /payloadHosts = perHostBuildIds \? Object\.keys\(perHostBuildIds\)\.filter\(\(h\) => h !== ""\) : \[\];/, "the build map's keys, the local one aside, taken at every payload");
  assert.ok(!FEED.includes('for (const a of asks) if (hostOf(a.sid) !== "") return true;'), "no card-based reading: the removed loop, literally (the twelfth executed review: the earlier pin matched a form that never existed)");
  assert.doesNotMatch(FEED, /sessionsMeta\.some\(\(s\) => hostOf\(s\.sid\) !== ""\)/, "nor a session-based one: a remote card with no session row read as a single-kernel pane (the round-twelve verifier)");
  assert.match(FEED, /if \(federatedPane\(\)\) clearedStack\.length = 0;\s*\/\/[^\n]*\n\s+const batch = clearedStack\.pop\(\);/, "and pops none: the round trip");
  assert.match(FEED, /clearedStack\.push\(\.\.\.older\);/, "the older local entries stay below the rebuilt ones under a truncated frame");
  assert.match(FEED, /if \(!federatedPane\(\)\) pendingCleared\.clear\(\);/, "the single-kernel round trip releases every suppression; a federated pane waits for federation's word (round twelve)");
  assert.match(FEED, /\} else if \(m\.type === "undoRouted" && Array\.isArray\(m\.hosts\)\) \{/, "federation's word on where the undo went");
  assert.match(FEED, /    if \(federatedPane\(\)\) \{\n      for \(const id of Array\.from\(pendingCleared\)\) \{\n        const h = suppressedHostOf\(id\);/, "the checks on a federated pane alone, read at the send (the thirteenth executed review: a single-kernel pane wrote checks on its other pending clears)");
  assert.match(FEED, /const floor = ackHosts\.has\(c\.host\) \? c\.floor : c\.sentBuild;\n\s+if \(floor === undefined \|\| typeof built !== "number"\) continue;\n\s+if \(built > floor\)/, "the floor (round fifteen): the kernel's account on an accounting kernel, nothing released until it lands; the build seen at the send on an older one");
  assert.match(FEED, /function setUndoFloor\(host: string, seq: unknown, floor: unknown\): void \{\n\s+if \(typeof floor !== "number"\) return;\n\s+for \(const c of restoreChecks\.values\(\)\) if \(c\.host === host && \(typeof seq !== "number" \|\| c\.seq === seq\)\) c\.floor = floor;/, "an account's floor lands on the checks written for that undo on its own kernel alone (the post-merge review, M2); an account without a sequence on every check of its kernel");
  assert.match(FEED, /if \(op === "undoClear"\) setUndoFloor\(fromHost, m\.seq, m\.buildId\);/, "the refusal's and the reorder's frames carry the floor and the sequence");
  assert.match(FEED, /if \(typeof seq === "number"\) for \(const \[id, c\] of Array\.from\(restoreChecks\)\) if \(c\.host === host && c\.floor === undefined && typeof c\.seq === "number" && c\.seq < seq\) \{ restoreChecks\.delete\(id\); pendingCleared\.delete\(id\); \}/, "a later undo's account drops the kernel's older FLOORLESS checks: their accounts will never come (the second contributor's post-merge note on PR 2018)");
  assert.match(KERNEL, /except FileNotFoundError:\n\s+_CLEARED_STATS\["derived"\] \+= 1\n\s+_cleared_read_fault\[0\] = ""[^\n]*\n\s+return cur, ""\n\s+except \(OSError, ValueError\) as e:[\s\S]{0,1800}if _cleared_read_fault\[0\] != copy:\n\s+_cleared_read_fault\[0\] = copy\n\s+_clears_log_fault_note\("the read", e, kind="cleared-unreadable"\)[^\n]*\n\s+return cur, copy/, "an absent clears log stays silent; a present one that cannot be read, or is not text, reads as the empty uncached set and is SAID once per episode under the judge reader's kind for this file (the post-merge review of PR 2021; the round-one verifier of PR 2025)");
  assert.match(KERNEL, /_clears_log_fault_note\("the mute's clear rows", e, fsid=sid, goal=tops\)/, "the mute's clear rows record their refusal, the session and its tops on the row (round three of PR 2025)"); assert.match(KERNEL, /_clears_log_fault_note\("the episode boundary's clear rows", e, fsid=sid, goal=tops\)[^\n]*\n\s+return/, "and the episode boundary's, its settle skipped");
  assert.match(KERNEL, /def _clears_log_fault_note\(what, e, kind="clears-log", fsid="", goal=None\):[\s\S]{0,1400}if fsid:\n\s+line \+= " \(session %s\)" % fsid\[:8\]\n[\s\S]{0,200}jd\._log_judge_error\("romp", fsid or "", kind, note=line, goal=goal\)/, "the note helper names the session and the nodes where the writer knows them");
  // round three of PR 2025 (the second contributor's post-merge review of PR 2021)
  assert.match(FEED, /\} else if \(op === "undoClear" && !fromHost && !federatedPane\(\) && !Array\.isArray\(m\.batches\) && typeof m\.seq === "number" && undoPopped\.has\(m\.seq\)\) \{[\s\S]{0,1800}for \(const id of ids\) \{ pendingRestored\.delete\(id\); pendingCleared\.add\(id\); \}\n\s+asks = asks\.filter\(\(a\) => !ids\.includes\(a\.itemId\)\);\n\s+clearedStack\.push\(popped\);/, "an undo account with no stack and no ids says the kernel restored nothing: the click's batch goes back off and back on the stack, by the echoed sequence");
  assert.match(FEED, /if \(op === "undoClear" && typeof m\.seq === "number"\) undoPopped\.delete\(m\.seq\);/, "the record is spent on any account for that undo"); assert.match(FEED, /setUndoFloor\(typeof m\.host === "string" \? m\.host : "", m\.seq, m\.buildId\);\n\s+if \(typeof m\.seq === "number"\) undoPopped\.delete\(m\.seq\);/, "and on the landed undo's ack");
  assert.match(KERNEL, /return slot\[1\], slot\[2\]/, "the memo hit serves the fault beside the set"); assert.match(KERNEL, /if isinstance\(e, ValueError\) and key is not None:\n\s+_CLEARED_MEMO\["slot"\] = \(key, cur, copy\)/, "an undecodable log is memoized under its stat, its fault in the slot; the OSError road is not"); assert.match(KERNEL, /_CLEARED_MEMO\["slot"\] = \(key, cur, ""\)/, "a landed read's slot carries no fault");
  assert.equal((KERNEL.match(/if not isinstance\(o, dict\):\n\s+continue/g) || []).length >= 1 && (JUDGE.match(/if not isinstance\(o, dict\):\n\s+continue/g) || []).length >= 2, true, "the non-object row guard in the kernel's reader and the judge's two"); assert.equal((KERNEL.match(/if not isinstance\(iid, str\) or not iid:\n\s+continue/g) || []).length >= 1 && (JUDGE.match(/if not isinstance\(iid, str\) or not iid:\n\s+continue/g) || []).length >= 2, true, "and the string check on the id, per row");
  assert.match(JUDGE, /except \(OSError, ValueError\) as e:[^\n]*\n[^\n]*\n\s+_read_failed\(path_s, "cleared-unreadable", getattr\(_judge_ctx, "fsid", ""\), e\)/, "the judge's scan reads bytes that are not text through its cleared-unreadable arm"); assert.match(JUDGE, /except FileNotFoundError:\n\s+_read_ok\(path_s\)[^\n]*\n\s+except \(OSError, ValueError\) as e:[\s\S]{0,700}_read_failed\(path_s, "cleared-unreadable", fsid, e\)\n\s+else:\n\s+_read_ok\(path_s\)/, "the planner's context read too, the missing-file arm first, where a bare pass stood"); assert.match(JUDGE, /except OSError as e:\n\s+_file_store_fault\(fsid, e, "store-unreadable",/, "the store boundary keeps its OSError-only contract: a ValueError out of a loader is a bug and reaches the caller (the round-three verifier of PR 2025 reverted a widening here)"); assert.doesNotMatch(JUDGE, /except \(OSError, ValueError\) as e:\n\s+_file_store_fault/, "never widened");
  assert.match(KERNEL, /if popped:\n\s+skipped\[LEDGER_REORDER_KEY\][^\n]*\n\s+cur, _rfault = _cleared_ids_read\(\)[^\n]*\n(\s+#[^\n]*\n){0,4}\s+if _rfault:\n\s+skipped\[LEDGER_READ_KEY\][^\n]*\n\s+_reorder\(False, owed_ids, 1\)\n\s+return skipped\n\s+if not cur:/, "the undo reads the log again after the lock block, always: a peer's clear landing during the lock wait is the batch this press restores (the round-three verifier of PR 2025)"); assert.doesNotMatch(KERNEL, /\n    if owed_ids:\n\s+cur, _rfault = _cleared_ids_read\(\)/, "never only when something was owed");
  assert.match(FEED, /wsup` frame for the local kernel; for a remote one the relay socket's own reopen, federation's\n\/\/ `romp:hostRelayUp` event, listened for below, and the tunnel poll's `hostUp` frame as a second trigger/, "the header names the three reconnect triggers"); assert.match(FEED, /\(the romp:hostRelayUp listener above\), kept for the one case that event never covers: a relay socket that never opens again on this\n\s+\/\/ page while the poll's row reads up/, "the poll arm names the one case it covers, and the listener's place");
  assert.match(FEED, /const seq = \+\+undoSeq;[^\n]*\n\s+if \(batch && batch\.length\) \{\n\s+undoPopped\.set\(seq, batch\);/, "each click mints its sequence and keeps the batch it restored under it (round three of PR 2025)"); assert.match(FEED, /postMessage\(\{ type: "undoClear", seq \}\)/, "the sequence rides the send");
  assert.match(FEED, /restoreChecks\.set\(id, \{ host: h, sentBuild: seen, seq: typeof m\.seq === "number" \? m\.seq : undefined \}\);/, "the check carries the undo it was written for");
  assert.match(FEED, /if \(restoreChecks\.has\(id\)\) continue;\s+\/\/ a check stands until judged/, "a later undo does not re-arm a standing check for its own sequence");
  assert.match(FEED, /function dropChecksOnReconnect\(host: string\): void \{\n\s+for \(const \[id, c\] of Array\.from\(restoreChecks\)\) if \(c\.host === host\) \{ restoreChecks\.delete\(id\); pendingCleared\.delete\(id\); \}/, "a kernel's socket coming back drops its checks and their suppressions (the post-merge review, low 2)");
  assert.match(FEED, /\} else if \(m\.type === "wsup"\) \{\n\s+dropChecksOnReconnect\(""\);/, "the local kernel's reopen (the shim's frame)");
  assert.match(FEED, /window\.addEventListener\("romp:hostRelayUp", \(ev\) => \{ const h = String\(\(ev as CustomEvent\)\.detail\?\.host \|\| ""\); if \(h\) dropChecksOnReconnect\(h\); \}\);/, "a remote relay socket's own reopen: the exact event a redial fires (the post-merge note on PR 2018)");
  assert.match(FEED, /\} else if \(m\.type === "hostUp" && Array\.isArray\(m\.hosts\)\) \{[\s\S]{0,1000}for \(const h of m\.hosts\) if \(typeof h === "string" && h\) dropChecksOnReconnect\(h\);/, "the tunnel poll's word as a second trigger");
  assert.match(FED, /type: "undoRouted", hosts: hosts\.slice\(\), seq: typeof m\.seq === "number" \? m\.seq : undefined/, "the routing frame carries the sequence");
  assert.match(KERNEL, /frame\["seq"\] = seq/, "the kernel echoes it on every undo account");
  assert.match(KERNEL, /with _client_lock\(client\):\n\s+client\["floorPending"\] = _floor/, "the pressing client's floor marked pending on an undo account (the post-merge review, M1; round two of PR 2018: a slot pop could land between an in-flight build's claim and its send)");
  assert.match(KERNEL, /fp = c\.get\("floorPending"\) if ftype == "feed" else None\n\s+if fp is not None:[\s\S]{0,700}sig="%s\|floor:%s\|build:%s" % \(sig, fp, bid\)\)\n\s+if went and isinstance\(bid, int\) and bid > fp:\n\s+c\.pop\("floorPending", None\)/, "while the floor is unanswered every feed build to that client goes whole, its signature carrying its build id, until one past the floor has gone");
  assert.match(FEED, /\} else if \(m\.type === "undoAck"\) \{/, "the landed undo's ack");
  assert.match(FED, /if \(out\.type === "err" \|\| out\.type === "undoAck"\) out\.host = host;/, "federation stamps the ack like the other accounts");
  assert.match(KERNEL, /_floor = _feed_build_id\[0\] if gesture == "undo" else None/, "the kernel's floor: the build counter as the undo is processed (claimed before a build's read)");
  assert.match(KERNEL, /frame\["buildId"\] = _floor/, "on every undo account");
  assert.match(KERNEL, /_ack = \{"type": "undoAck", "op": op or "", "buildId": _floor\}\s+if seq is not None:\s+_ack\["seq"\] = seq\s+client\["send"\]\(json\.dumps\(_ack\)\)/, "and the ack for a landed undo, the sequence echoed on it (the post-merge review, M2)");
  assert.match(KERNEL, /"undoAck": True,/, "the payload says this kernel accounts so");
  assert.match(FED, /if \(f\.undoAck === true\) ackHosts\.push\(h\);/, "the merge names the accounting kernels");
  assert.match(FEED, /if \(seen === undefined\) \{ pendingCleared\.delete\(id\); restoreChecks\.delete\(id\); continue; \}/, "a kernel with no build on record: the click-time release, never a baseline of zero (the round-twelve verifier's MEDIUM)");
  assert.doesNotMatch(FEED, /lastSeenBuild\.get\(h\) \?\? 0/, "no zero baseline anywhere");
  assert.match(FEED, /if \(\(!perHostBuildIds \|\| typeof perHostBuildIds\[""\] !== "number"\) && typeof m\.buildId === "number"\) lastSeenBuild\.set\("", m\.buildId\);/, "the local kernel's seen build from the payload's own when the map lacks the local key");
  assert.match(FEED, /if \(built > floor\) \{ pendingCleared\.delete\(a\.itemId\); restoreChecks\.delete\(a\.itemId\); \}/, "a suppression ends on the evidence: the card's own kernel's payload, built past its check's floor, listing it; the check leaves once judged");
  assert.match(FEED, /if \(typeof built === "number" && seen !== undefined && built < seen\) \{ c\.sentBuild = -1; c\.floor = -1; \}/, "a build below the last seen is the kernel's restart: the check re-bases to the new life, its floor too (the twelfth executed review; round fifteen)");
  assert.match(FEED, /function releaseRestoredByEvidence\(incomingAsks: AskItem\[\], m: any\): void \{\n  for \(const id of Array\.from\(restoreChecks\.keys\(\)\)\) if \(!pendingCleared\.has\(id\)\) restoreChecks\.delete\(id\);/, "no gate on the attachment inside the evidence path (a pane that flips to single-kernel keeps its checks; the twelfth executed review); a check whose suppression the absence rule ended leaves");
  assert.match(FEED, /  releaseRestoredByEvidence\(incomingAsks, m\);/, "called from the payload handler, apart from its absence-driven writers");
  assert.doesNotMatch(FEED, /lastClearHostsPage/, "no shadow of the routing on the page");
  assert.match(FED, /window\.dispatchEvent\(new MessageEvent\("message", \{ data: \{ type: "undoRouted", hosts: hosts\.slice\(\), seq: [^}]*\} \}\)\);/, "handed to the panes at the send, by the routing's owner");
  assert.match(FEED, /if \(op === "undoClear" && \(!federatedPane\(\) \|\| lastUndoHosts\.has\(fromHost\)\)\) clearUndoBusy\(\);/, "an undo's account from a kernel the undo went to clears the round trip's cue");
  assert.match(FEED, /if \(!federatedPane\(\) \|\| undoRoutedBuilt\(m\)\) clearUndoBusy\(\);/, "on a federated pane the payload clears the cue once every kernel the undo went to has built past the send (the second contributor's review); the backstop stands");
  // the page's record of cleared cards (the round-ten verifier): one source for the reconcile, pruned when a live payload shows the card, bounded
  assert.doesNotMatch(FEED, /for \(const e of clearedStack\) for \(const it of e\) known\.set/, "one source for the record, so the enumeration's mutant on it reds");
  assert.match(FEED, /for \(const id of Array\.from\(clearedItems\.keys\(\)\)\) if \(!pendingCleared\.has\(id\) && incomingAsks\.some\(\(a\) => a\.itemId === id\)\) clearedItems\.delete\(id\);/, "a record ends when a live payload shows the card unsuppressed");
  assert.match(FEED, /^const CLEARED_ITEMS_CAP = 200;/m);
  assert.match(FEED, /asks = asks\.filter\(\(a\) => \{ if \(!hidden\.has\(a\.itemId\)\) return true; recordCleared\(a\); return false; \}\);/, "a card the reconcile hides enters the record with its live copy, for the next frame of the same press");
  assert.match(FEED, /function evictClearedRecords\(writing: Iterable<string>\): void \{[\s\S]{0,700}if \(!held\.has\(id\)\) clearedItems\.delete\(id\);/, "bounded, the oldest evictable first: never a record under suppression, on the stack, or in the batch being written (rounds twelve and thirteen)");
  assert.equal((FEED.match(/clearedItems\.set\(/g) || []).length, 1, "one writer of the record (recordCleared): a second direct write would bypass the cap (the twelfth executed review)");
  assert.equal((FEED.match(/evictClearedRecords\(/g) || []).length, 4, "the definition and its three calls: after the federated return, after the splice, after the reconcile's hiding");
  assert.equal((FEED.match(/recordCleared\(/g) || []).length, 3, "the two writers (a clear, the reconcile hiding a card) and the definition: no write bypasses the cap");
  assert.match(KERNEL, /^LEDGER_BATCHES_ON_WIRE = 20/m, "the stack on the wire is bounded (plans\/needs-you.md)");
  assert.match(KERNEL, /def _ledger_batches\(limit=LEDGER_BATCHES_ON_WIRE\):/);
  assert.match(KERNEL, /cur, fault = _cleared_ids_read\(\)\n\s+by = \{\}[\s\S]{0,1200}return \(\[owed\] if owed else \[\]\) \+ out\[:limit\], owed, len\(out\), fault/, "the stack helper returns its read's fault beside the stack (the round-two verifier of PR 2025)"); assert.match(KERNEL, /_lb\[0\] = _ledger_batches\(\)[^\n]*\n\s+if not _lb\[0\]\[3\]:[^\n]*\n[^\n]*\n\s+frame\["batches"\], frame\["owedBatch"\], frame\["batchesTotal"\] = _lb\[0\]\[:3\]/, "and the account's gate reads that return, never the module flag");
  assert.match(KERNEL, /return \(\[owed\] if owed else \[\]\) \+ out\[:limit\], owed, len\(out\)/, "the newest batches within the bound, the owed ids, the count");
  assert.match(FEED, /const truncated = typeof m\.batchesTotal === "number" && m\.batchesTotal > bats\.length - \(owedB\.length \? 1 : 0\);/, "a frame that left older batches out says so (round ten)");
  assert.match(FEED, /reconcileClearedStack\(bats, owedB, truncated, refusedIds\);/);
  assert.match(FEED, /if \(truncated && !named\.has\(id\) && !cleared\.has\(id\)\) continue;/, "a suppression the truncated frame neither names nor carries stays");
  assert.match(FEED, /function pushClearedEntry\(entry: AskItem\[\]\): void \{\n  for \(const it of entry\) recordCleared\(it\);\n  const writing = entry\.map\(\(it\) => it\.itemId\);\n  if \(federatedPane\(\)\) \{ evictClearedRecords\(writing\); return; \}[^\n]*\n  let i = clearedStack\.length;\n  const owedIds = new Set<string>\(\);/, "the record first, the batch held through the cap; a federated pane keeps no stack");
  assert.match(FEED, /if \(rest\.length\) clearedStack\.splice\(i, 0, rest\);\n  evictClearedRecords\(writing\);/, "the cap after the entry is on the stack, this batch held (the twelfth executed review: the batch's own oldest members went at the 201st record)");
  assert.match(FEED, /const rest = entry\.filter\(\(it\) => !owedIds\.has\(it\.itemId\)\);\n  if \(rest\.length\) clearedStack\.splice\(i, 0, rest\);/);
  assert.match(FEED, /function reconcileClearedStack\(batches: string\[\]\[\], owedBatch: string\[\], truncated = false, namedIds: string\[\] = \[\]\): void \{/);
  assert.equal((FEED.match(/pushClearedEntry\(/g) || []).length, 5, "the four writers (a card's Clear, a group's, a session's Clear all, the board's Clear all) and the definition");
  assert.match(KERNEL, /frame\["owedIds"\] = \[str\(i\) for i in owed\]/);
  assert.doesNotMatch(KERNEL, /The owed cards came back, but romp could not clear the note/, "the owed-write account, filed before the flag step, claims nothing about the restore");
  // the owed note (lows 3 and 4 of the fourth review, the round-four verifier's medium): one lock across the section, the rewrite with what is still owed, none after an unreadable note
  assert.match(KERNEL, /_OWED_LOCK = threading\.RLock\(\)/);
  assert.match(KERNEL, /    with _OWED_LOCK:\n[\s\S]{0,900}_rerr = _owed_load\(\)/, "the read under the lock _undo_clear holds across the section");
  assert.match(KERNEL, /if not _rerr:\n[\s\S]{0,700}_werr = _owed_rewrite\(list\(_rejournal_owed\)\)/, "the rewrite with the ids still owed, skipped after an unreadable note");
  assert.doesNotMatch(KERNEL, /_owed_rewrite\(\[\]\)/, "never a literal empty list");
  assert.match(KERNEL, /popped = \[i for i in popped if i not in owed_ids\]/, "a re-journaled id in the newest batch is restored this press, not named as parked");
  // each account names only its own ids (the third review's high): a skipped session's frame carries its own out of the batch
  assert.match(KERNEL, /_ids = \[i for i in _batch if \(i\.startswith\("notice:%s:" % sid\) if notices else \(not i\.startswith\("notice:"\) and i\.rsplit\(":", 1\)\[0\] == sid\)\)\]/, "a skipped session's own ids out of the batch");
  // the dialogs attach their box (the verifier's medium B, pre-existing on main): the behaviour rides the feed lab; this pins both functions carry the append
  assert.equal((FEED.match(/overlay\.appendChild\(box\);/g) || []).length, 3, "the quarantine dialog's, and now showErrDialog's and showPickerDialog's");
});
